apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client-gateway
  name: client-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client-gateway
    spec:
      containers:
        - image: northamerica-south1-docker.pkg.dev/micrservicesnestjs/lacaja/client-gateway
          name: client-gateway
          resources: {}
status: {}
