apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres-nodeport
  name: postgres-nodeport
spec:
  ports:
  - name: "5432"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-nodeport
  type: NodePort
status:
  loadBalancer: {}
